//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BK.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class announcement
    {
        public int AnnoucementID { get; set; }
        public string AnnoucementTitle { get; set; }
        public string AnnoucementText { get; set; }
        public System.DateTime ExpiresOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual familymember familymember { get; set; }
        public virtual familymember familymember1 { get; set; }
    }
}
