//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BK.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int EventID { get; set; }
        public int EventTypeId { get; set; }
        public string EventTitle { get; set; }
        public string EventText { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<System.TimeSpan> EventTime { get; set; }
        public System.DateTime ExpiresOn { get; set; }
        public int FamilyID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual family family { get; set; }
        public virtual familymember familymember { get; set; }
        public virtual familymember familymember1 { get; set; }
        public virtual lkeventtype lkeventtype { get; set; }
    }
}
