//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BK.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int LoginID { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastLoginOn { get; set; }
        public int FamilyMemberID { get; set; }
        public string PasswordUID { get; set; }
        public bool Active { get; set; }
    
        public virtual familymember familymember { get; set; }
    }
}
