//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BK.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matrimonial
    {
        public int MatrimonialID { get; set; }
        public int MemberID { get; set; }
        public int MaternalNukhID { get; set; }
        public Nullable<System.TimeSpan> BirthTime { get; set; }
        public int MaritalStatusID { get; set; }
        public int Height { get; set; }
        public int Weight { get; set; }
        public int BodyTypeID { get; set; }
        public int ComplexionTypeID { get; set; }
        public bool Smoke { get; set; }
        public bool Tobacco { get; set; }
        public bool Alcohol { get; set; }
        public bool Disability { get; set; }
        public bool Vegetarian { get; set; }
        public bool OwnHome { get; set; }
        public string Mangal { get; set; }
        public int MonthlyIncome { get; set; }
        public string Language { get; set; }
        public string ProfileText { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
