//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BK.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matrimonial
    {
        public int MatrimonialID { get; set; }
        public int MemberID { get; set; }
        public string MaternalNukh { get; set; }
        public Nullable<System.TimeSpan> BirthTime { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> Height { get; set; }
        public string BodyType { get; set; }
        public string Complexion { get; set; }
        public string Smoke { get; set; }
        public string Drink { get; set; }
        public bool Disability { get; set; }
        public string Diet { get; set; }
        public string AnnualIncome { get; set; }
        public string Language { get; set; }
        public string ProfileText { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
