import { Component, OnInit } from '@angular/core';
import { MatTableDataSource } from '@angular/material';

@Component({
  selector: 'app-gotra',
  templateUrl: './gotra.component.html',
  styleUrls: ['./gotra.component.scss']
})
export class GotraComponent implements OnInit {

  constructor() { }

  displayedColumns = ['gotraName', 'nukh1', 'nukh2', 'nukh3', 'nukh4', 'nukh5', 'nukh6', 'nukh7'];

  dataSource = new MatTableDataSource<GotraModel>(GOTRA_DATA);

  ngOnInit() {
  }

}

export interface GotraModel {
  gotraName: string;
  nukh1: string;
  nukh2: string;
  nukh3: string;
  nukh4: string;
  nukh5: string;
  nukh6: string;
  nukh7: string;  
}

const GOTRA_DATA: GotraModel[] = [
  {    
    gotraName: "Jamdagngodhiya",
    nukh1: "Jesbahar",
    nukh2: "Jajal",
    nukh3: "Jogi",
    nukh4: "Jarecha",
    nukh5: "Jagar",
    nukh6: "Lula",
    nukh7: "",    
  },  
  {    
    gotraName: "Mandata",
    nukh1: "Mamtur",
    nukh2: "Mavarba",
    nukh3: "Mavdasya",
    nukh4: "Marthak",
    nukh5: "Maniyar",
    nukh6: "Mohan",
    nukh7: "Vachha",    
  },  
  {    
    gotraName: "Dakshan",
    nukh1: "Dubal",
    nukh2: "Kosara",
    nukh3: "Ghanghra",
    nukh4: "Dhulera",
    nukh5: "Darmriya",
    nukh6: "Dearcha",
    nukh7: "Gadiy",    
  },  
  {    
    gotraName: "Sudarshan",
    nukh1: "Sonishor",
    nukh2: "Seta",
    nukh3: "Sodiya",
    nukh4: "Damra",
    nukh5: "Chacha",
    nukh6: "Jagwarth",
    nukh7: "",    
  },  
  {    
    gotraName: "Shandilay",
    nukh1: "Sanischara",
    nukh2: "Sonpal",
    nukh3: "Sandhava",
    nukh4: "Sodeji",
    nukh5: "",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Uttari",
    nukh1: "Ashra",
    nukh2: "Mamlatura",
    nukh3: "Dagagaden",
    nukh4: "Bagal",
    nukh5: "Dakna",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Kaushik",
    nukh1: "Kakaiya",
    nukh2: "Kaku",
    nukh3: "Kukar",
    nukh4: "Lavanhar",
    nukh5: "Katkiy",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Agastya",
    nukh1: "Arora",
    nukh2: "Asalchinva",
    nukh3: "Jagodhar",
    nukh4: "Tatriya",
    nukh5: "",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Shankhpal",
    nukh1: "Sorthiya",
    nukh2: "Soneji",
    nukh3: "Degra",
    nukh4: "Desar",
    nukh5: "Godiya",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Bhardwaj",
    nukh1: "Bhoot",
    nukh2: "Bheva",
    nukh3: "Bichhra",
    nukh4: "Kukar",
    nukh5: "Bhekshan",
    nukh6: "Bhdhar",
    nukh7: "Bhahel",    
  },  
  {    
    gotraName: "Rahugan",
    nukh1: "Rasputra",
    nukh2: "Rasbhukhra",
    nukh3: "Raja",
    nukh4: "Barra",
    nukh5: "Ravsya",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Dhanjiy",
    nukh1: "Dhandha",
    nukh2: "Dharare",
    nukh3: "Dhandenya",
    nukh4: "Dhada",
    nukh5: "Dhrujakhat",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Sudhgal",
    nukh1: "Makriya",
    nukh2: "Makori",
    nukh3: "Meghiya",
    nukh4: "Machhar",
    nukh5: "Mer",
    nukh6: "Gurnara",
    nukh7: "",    
  },  
  {    
    gotraName: "Badrayan",
    nukh1: "Bagriya",
    nukh2: "Borachya",
    nukh3: "Hargan",
    nukh4: "Harshana",
    nukh5: "",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Gargiy",
    nukh1: "Gajkaran",
    nukh2: "Gumra",
    nukh3: "Chakla",
    nukh4: "Chhuchha",
    nukh5: "",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Vatsa",
    nukh1: "Vama",
    nukh2: "Vajri",
    nukh3: "Vinchhi",
    nukh4: "Vili",
    nukh5: "Chamariya",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Gautam",
    nukh1: "Girachh",
    nukh2: "Goratela",
    nukh3: "Dhela",
    nukh4: "Madhur",
    nukh5: "Madhu",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Vamdeo",
    nukh1: "Veredre",
    nukh2: "Lemriya",
    nukh3: "Liya",
    nukh4: "Luliy",
    nukh5: "",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Kashyap",
    nukh1: "Katbamna",
    nukh2: "Kandhara",
    nukh3: "Hargan",
    nukh4: "Hanja",
    nukh5: "",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Kamak",
    nukh1: "Keherach",
    nukh2: "Karcha",
    nukh3: "Tokle",
    nukh4: "Tangra",
    nukh5: "Dak",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Kanav",
    nukh1: "Keri",
    nukh2: "Dagiya",
    nukh3: "Daiyani",
    nukh4: "Tandon",
    nukh5: "",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Vaman",
    nukh1: "Vadel",
    nukh2: "Dhavriya",
    nukh3: "Dror",
    nukh4: "Dodiy",
    nukh5: "",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Taitar",
    nukh1: "Tenyodha",
    nukh2: "Thegra",
    nukh3: "Duda",
    nukh4: "Drodriya",
    nukh5: "Dadagan",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Vashishtha",
    nukh1: "Valel",
    nukh2: "Chhatbar",
    nukh3: "Chhanang",
    nukh4: "Mer",
    nukh5: "Jil",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Bhabhroy",
    nukh1: "Vasoma",
    nukh2: "Vadva",
    nukh3: "Papuriya",
    nukh4: "Padia",
    nukh5: "",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Nartyojan",
    nukh1: "Nansi",
    nukh2: "Neman",
    nukh3: "Naysar",
    nukh4: "Negu",
    nukh5: "Nan",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Rushan",
    nukh1: "Karatela",
    nukh2: "Karchala",
    nukh3: "Khakhar",
    nukh4: "Loaa",
    nukh5: "",
    nukh6: "",
    nukh7: "",    
  },  
  {    
    gotraName: "Parashar",
    nukh1: "Panjabhoot",
    nukh2: "Patar",
    nukh3: "Mamotra",
    nukh4: "Paitermer",
    nukh5: "",
    nukh6: "",
    nukh7: "",    
  }, 
];
